import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import '@/styles/globals.css';

import LayoutCore from '@/components/layout/LayoutCore';

import { configFonts } from '@/locales/config';

export const metadata: Metadata = {
  title: 'Setare YeK Travel Nest',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}): Promise<JSX.Element> {
  // Providing all locales to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} dir={configFonts[locale]?.dir}>
      <body className={configFonts[locale]?.font || ''}>
        <NextIntlClientProvider messages={messages}>
          <LayoutCore>{children}</LayoutCore>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
